# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skillbelt < Formula
  desc "A package manager for agent skills"
  homepage "https://github.com/carlosafonso/skillbelt"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/carlosafonso/skillbelt/releases/download/v0.1.4/skillbelt_darwin_amd64.tar.gz"
      sha256 "88392b4a5869b536e4494600a82cb07b6ecb1a993bfdf9588220c3457a0beb5f"

      define_method(:install) do
        bin.install "skillbelt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/carlosafonso/skillbelt/releases/download/v0.1.4/skillbelt_darwin_arm64.tar.gz"
      sha256 "7942de6acd778b2c868c62b5570d27df4cfcb8afea59f7e51ce7bd152f7fb702"

      define_method(:install) do
        bin.install "skillbelt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/carlosafonso/skillbelt/releases/download/v0.1.4/skillbelt_linux_amd64.tar.gz"
      sha256 "82e5b1011b47c7619c9471d1c8578075b2a405cd989f72fb74bbbd47728e8986"
      define_method(:install) do
        bin.install "skillbelt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/carlosafonso/skillbelt/releases/download/v0.1.4/skillbelt_linux_arm64.tar.gz"
      sha256 "ddeac816843bdb73120d6e0a7ac724c6567aec8784c2274a97d76fbd4bebff87"
      define_method(:install) do
        bin.install "skillbelt"
      end
    end
  end

  test do
    system "#{bin}/skillbelt", "--help"
  end
end
